// Copyright (c) 2023 LG Electronics, Inc. All rights reserved.
// Copyright 2021 Sony Group Corporation. All rights reserved.
// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter_tools/src/base/file_system.dart';
import 'package:flutter_tools/src/project.dart';

import 'webos_plugins.dart';

/// Escapes [value] for use inside a CMake double-quoted string: backslash,
/// double-quote and dollar, so injected paths/names cannot break or inject
/// CMake. Use when embedding a value alongside literal `${...}` refs.
String cmakeEscape(String value) =>
    value.replaceAll(r'\', r'\\').replaceAll('"', r'\"').replaceAll(r'$', r'\$');

/// [cmakeEscape] wrapped as a complete CMake double-quoted literal.
String cmakeQuoted(String value) => '"${cmakeEscape(value)}"';

/// The webOS sub project.
class WebosProject extends FlutterProjectPlatform implements CmakeBasedProject {
  WebosProject.fromFlutter(this.parent);

  @override
  final FlutterProject parent;

  @override
  String get pluginConfigKey => WebosPlugin.kConfigKey;

  String get _childDirectory => 'webos';

  @override
  bool existsSync() => editableDirectory.existsSync() && cmakeFile.existsSync();

  @override
  File get cmakeFile => editableDirectory.childFile('CMakeLists.txt');

  @override
  File get managedCmakeFile => managedDirectory.childFile('CMakeLists.txt');

  @override
  File get generatedCmakeConfigFile => ephemeralDirectory.childFile('generated_config.cmake');

  /// The single webOS build graph that the committed `CMakeLists.txt`
  /// includes. Generated by `WebosBuildGraph` in `webos_build_graph.dart`;
  /// owns artifact data, build-environment setup, and the install section.
  File get webosBuildFile => ephemeralDirectory.childFile('webos_build.cmake');

  /// Static compile-settings fragment shipped from
  /// `flutter-webos/lib/cmake/webos_compile_settings.cmake`. Provides the
  /// SYSTEM include and APPLY_STANDARD_SETTINGS function to user templates.
  File get webosCompileSettingsFile => ephemeralDirectory.childFile('webos_compile_settings.cmake');

  /// runner_base sources copied into ephemeral by NativeBundle.
  Directory get runnerBaseDirectory => ephemeralDirectory.childDirectory('runner_base');

  /// POSIX path of [entityPath] relative to [editableDirectory] (the webos/
  /// dir that hosts the committed CMakeLists). Single source of the ephemeral
  /// layout the generated CMake refers to.
  String _relFromEditable(String entityPath) {
    final FileSystem fs = editableDirectory.fileSystem;
    return fs.path.split(fs.path.relative(entityPath, from: editableDirectory.path)).join('/');
  }

  String get webosCompileSettingsRel => _relFromEditable(webosCompileSettingsFile.path);
  String get runnerBaseRel => _relFromEditable(runnerBaseDirectory.path);

  @override
  File get generatedPluginCmakeFile => managedDirectory.childFile('generated_plugins.cmake');

  @override
  Directory get pluginSymlinkDirectory => ephemeralDirectory.childDirectory('.plugin_symlinks');

  Directory get editableDirectory => parent.directory.childDirectory(_childDirectory);

  Directory get managedDirectory => editableDirectory.childDirectory('flutter');

  Directory get ephemeralDirectory => managedDirectory.childDirectory('ephemeral');

  Future<void> ensureReadyForPlatformSpecificTooling() async {
    await refreshWebosPluginsList(parent);
  }
}
