// Copyright (c) 2026 LG Electronics, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'webos_cmake_project.dart';

/// Resolved inputs for one native_app build graph emission.
class WebosBuildInputs {
  const WebosBuildInputs({
    required this.binaryName,
    required this.engineLibrary,
    required this.embedderLibrary,
    required this.commonLibrary,
    required this.icuDataFile,
    required this.aotLibrary,
    required this.projectBuildDir,
  });

  final String binaryName;
  final String engineLibrary;
  final String embedderLibrary;
  final String commonLibrary;
  final String icuDataFile;
  final String aotLibrary;
  final String projectBuildDir;
}

/// Emits the single webOS build graph that the committed `CMakeLists.txt`
/// includes:
///
///   `<project>/webos/flutter/ephemeral/webos_build.cmake`
///
/// One file owns artifact data (paths + install bundle layout), the
/// build-environment setup (find-root modes, RPATH, embedder/runner_base
/// wiring), the executable/link rules, and the single ordered install
/// section. Ephemeral paths come from the [WebosProject] getters; nothing
/// is hard-coded here.
class WebosBuildGraph {
  WebosBuildGraph(this.project, this.inputs);

  final WebosProject project;
  final WebosBuildInputs inputs;

  void emit() {
    _writeManagedCmake();
    project.webosBuildFile
      ..createSync(recursive: true)
      ..writeAsStringSync(_render());
  }

  /// Writes `<project>/webos/flutter/CMakeLists.txt` only when absent, so
  /// templates that ship their own managed CMakeLists (e.g. webos_app) keep
  /// theirs untouched. Deliberately asymmetric with the build graph, which
  /// is always overwritten.
  void _writeManagedCmake() {
    if (project.managedCmakeFile.existsSync()) {
      return;
    }
    const content = r'''
# Generated by flutter-webos. Do not commit.

cmake_minimum_required(VERSION 3.15)

set(EPHEMERAL_DIR "${CMAKE_CURRENT_SOURCE_DIR}/ephemeral")

include(${EPHEMERAL_DIR}/generated_config.cmake)
''';
    project.managedCmakeFile
      ..createSync(recursive: true)
      ..writeAsStringSync(content);
  }

  String _render() => '''
# Generated code do not commit.
# webOS build graph — populated by flutter-webos NativeBundle.

set(CMAKE_CXX_STANDARD 17)

# Defensive fallback if NDK toolchain file isn't loaded.
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_INSTALL_RPATH "\$ORIGIN;\$ORIGIN/lib;.")
set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)

set(BINARY_NAME ${cmakeQuoted(inputs.binaryName)})
set(FLUTTER_MANAGED_DIR "\${CMAKE_CURRENT_SOURCE_DIR}/flutter")

include(\${CMAKE_CURRENT_SOURCE_DIR}/${project.webosCompileSettingsRel})

# === artifact data ===
# Self-contained: resolves paths relative to this file's location.
set(EPHEMERAL_DIR "\${CMAKE_CURRENT_LIST_DIR}")

set(FLUTTER_LIBRARY          "\${EPHEMERAL_DIR}/${cmakeEscape(inputs.engineLibrary)}")
set(FLUTTER_EMBEDDER_LIBRARY "\${EPHEMERAL_DIR}/${cmakeEscape(inputs.embedderLibrary)}")
set(FLUTTER_COMMON_LIBRARY   "\${EPHEMERAL_DIR}/${cmakeEscape(inputs.commonLibrary)}")
set(FLUTTER_ICU_DATA_FILE    "\${EPHEMERAL_DIR}/${cmakeEscape(inputs.icuDataFile)}")
set(AOT_LIBRARY              "\${EPHEMERAL_DIR}/${cmakeEscape(inputs.aotLibrary)}")
set(PROJECT_BUILD_DIR        ${cmakeQuoted(inputs.projectBuildDir)})

set(BUILD_BUNDLE_DIR "\${PROJECT_BINARY_DIR}/bundle")
if(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
  set(CMAKE_INSTALL_PREFIX "\${BUILD_BUNDLE_DIR}" CACHE PATH "..." FORCE)
endif()

set(INSTALL_BUNDLE_DATA_DIR "\${CMAKE_INSTALL_PREFIX}/data")
set(INSTALL_BUNDLE_LIB_DIR  "\${CMAKE_INSTALL_PREFIX}/lib")

add_subdirectory(\${FLUTTER_MANAGED_DIR})

# Plugins resolve embedder headers via target_link_libraries(... flutter).
add_library(flutter INTERFACE)
target_include_directories(flutter INTERFACE
  "\${FLUTTER_MANAGED_DIR}/ephemeral/include"
)
target_link_libraries(flutter INTERFACE "\${FLUTTER_COMMON_LIBRARY}")

add_subdirectory(
  \${CMAKE_CURRENT_SOURCE_DIR}/${project.runnerBaseRel}
  \${CMAKE_CURRENT_BINARY_DIR}/runner_base
)

include(\${CMAKE_CURRENT_SOURCE_DIR}/runner/user_build.cmake)

set(USER_APP_SRCS
  \${USER_APP_EXTRA_SRCS}
  flutter/generated_plugin_registrant.cc
)
set(USER_APP_INCLUDE_DIRS
  flutter/ephemeral/include
  flutter/ephemeral/include/flutter
  \${USER_APP_EXTRA_INCLUDE_DIRS}
)
set(USER_APP_LIBRARIES
  runner_base
  \${FLUTTER_EMBEDDER_LIBRARY}
)

add_executable(\${BINARY_NAME}
  \${USER_APP_SRCS}
)
target_include_directories(\${BINARY_NAME} PRIVATE
  \${USER_APP_INCLUDE_DIRS}
)
apply_standard_settings(\${BINARY_NAME})
target_link_libraries(\${BINARY_NAME} PRIVATE
  atomic
  \${USER_APP_LIBRARIES}
)

# generated_plugins.cmake links plugins into the runner target, so it must run
# after add_executable; WEBOS_PLUGIN_INTERFACE_LIBRARY names that target.
set(WEBOS_PLUGIN_INTERFACE_LIBRARY \${BINARY_NAME})
include(\${FLUTTER_MANAGED_DIR}/generated_plugins.cmake)

# === install ===
# Single section. Order is load-bearing: clean the bundle dir first, then
# runtime artifacts, then the target.
install(CODE "
  file(REMOVE_RECURSE \\"\${BUILD_BUNDLE_DIR}/\\")
  " COMPONENT Runtime)

install(FILES "\${FLUTTER_ICU_DATA_FILE}"    DESTINATION "\${INSTALL_BUNDLE_DATA_DIR}" COMPONENT Runtime)
install(FILES "\${FLUTTER_LIBRARY}"          DESTINATION "\${INSTALL_BUNDLE_LIB_DIR}"  COMPONENT Runtime)
install(FILES "\${FLUTTER_EMBEDDER_LIBRARY}" DESTINATION "\${INSTALL_BUNDLE_LIB_DIR}"  COMPONENT Runtime)
install(FILES "\${FLUTTER_COMMON_LIBRARY}"   DESTINATION "\${INSTALL_BUNDLE_LIB_DIR}"  COMPONENT Runtime)

if(PLUGIN_BUNDLED_LIBRARIES)
  foreach(bundled_library \${PLUGIN_BUNDLED_LIBRARIES})
    install(FILES "\${bundled_library}" DESTINATION "\${INSTALL_BUNDLE_LIB_DIR}" COMPONENT Runtime)
  endforeach(bundled_library)
endif()

# Fully re-copy flutter_assets on each build to avoid stale files.
install(DIRECTORY "\${PROJECT_BUILD_DIR}/flutter_assets"
  DESTINATION "\${INSTALL_BUNDLE_DATA_DIR}" COMPONENT Runtime)

# Install the AOT library on non-Debug builds only.
if(NOT CMAKE_BUILD_TYPE MATCHES "Debug")
  install(FILES "\${AOT_LIBRARY}" DESTINATION "\${INSTALL_BUNDLE_LIB_DIR}" COMPONENT Runtime)
endif()

install(TARGETS \${BINARY_NAME} RUNTIME
        PERMISSIONS OWNER_EXECUTE OWNER_READ
        DESTINATION "\${CMAKE_INSTALL_PREFIX}"
        COMPONENT Runtime)
''';
}
